version: '3.1'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8
    network_mode: "host"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aykirilar
      - MYSQL_PASSWORD=aykirilar
      - MYSQL_USER=aykirilar
      - MYSQL_DATABASE=aykirilar
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
  app:
    build: .
    container_name: app
    hostname: app
    depends_on:
      - mysql
    network_mode: "host"