spring:
  application:
    name: trading-data-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aykirilar
    username: aykirilar
    password: aykirilar
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: SpringBootJPAHikariCP
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 1000000
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  shutdown: graceful
  port: 8080
logging:
  level:
    org.zalando.logbook: TRACE